version: '3.8'

services:
  app:
    image: kovrz/weather-app:latest
    restart: always
    environment:
      - OPENWEATHER_API_KEY=58d10a9101aac36473b919102c658c06

    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
